# Generated by Django 4.2.7 on 2026-09-27 14:42

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=api.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('instructor', models.CharField(blank=True, default='', max_length=100)),
                ('credits', models.IntegerField(default=3)),
                ('color', models.CharField(default='#3b82d4', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('study_minutes', models.IntegerField(default=0)),
                ('distraction_minutes', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.CharField(default=api.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('metric', models.CharField(default='completion', max_length=50)),
                ('target_value', models.IntegerField(default=100)),
                ('current_value', models.IntegerField(default=0)),
                ('achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.CharField(default=api.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(default='General', max_length=100)),
                ('type', models.CharField(choices=[('study', 'Study'), ('class', 'Class'), ('break', 'Break'), ('exercise', 'Exercise')], default='study', max_length=20)),
                ('color', models.CharField(default='#3b82d4', max_length=20)),
                ('recurring', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SemesterEvent',
            fields=[
                ('id', models.CharField(default=api.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('exam', 'Exam'), ('holiday', 'Holiday'), ('submission', 'Submission'), ('other', 'Other')], default='other', max_length=20)),
                ('course', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=api.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('deadline', models.DateTimeField()),
                ('course', models.CharField(default='General', max_length=100)),
                ('type', models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam'), ('project', 'Project'), ('reading', 'Reading'), ('other', 'Other')], default='assignment', max_length=20)),
                ('estimated_hours', models.FloatField(default=2.0)),
                ('weight', models.IntegerField(default=5)),
                ('tags', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Student', max_length=100)),
                ('study_goal_hours', models.IntegerField(default=6)),
                ('pomodoro_work', models.IntegerField(default=25)),
                ('pomodoro_break', models.IntegerField(default=5)),
                ('preferred_study_time', models.CharField(default='morning', max_length=20)),
                ('subjects', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.CharField(default=api.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('distraction_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('tired', 'Tired'), ('stressed', 'Stressed')], default='neutral', max_length=10)),
                ('productivity', models.IntegerField(default=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.task')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
