# Generated by Django 6.0.5 on 2026-07-27 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_category_task_created_at_task_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', 'due_date']},
        ),
        migrations.AddField(
            model_name='studysession',
            name='technique',
            field=models.CharField(choices=[('normal', 'Normal Study'), ('pomodoro', 'Pomodoro (25/5)'), ('deep', 'Deep Work Block'), ('review', 'Review & Recap')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.CharField(choices=[('none', 'No Reminder'), ('1_day', '1 Day Before'), ('3_days', '3 Days Before'), ('1_week', '1 Week Before')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='SemesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=50)),
                ('goal', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
